# Generated by Django 4.2.11 on 2024-04-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
